### ISSUE TITLE
4. Tipp (Zeile15)

### ISSUE THREAD

**Issue by Xenonauts** [Xenonauts/Xenonauts_DE#74]
"Your game includes a free novella that tells the story of the 1958 Iceland Incident and the formation of the Xenonauts.

It can be found under the Extras tab of the launcher."

**Comment by psi-coder** [comment]
_"Im Lieferumfang Ihres Spiels ist eine kostenlose Erzählung enthalten, die über den Zwischenfall auf Island im Jahr 1958 and die anschließende Gründung der Xenonauten berichtet.
Sie finden sie im Spielstarter unter dem Reiter 'Extras'."_

**Comment by goethesfaust** [comment]
"Im Lieferumfang des Spiels ist eine kostenlose Novelle im PDF-Format enthalten, die über den Island-Zwischenfall im Jahr 1958 und die anschließende Gründung der Xenonauts berichtet.
Du findest sie im Spielstarter unter dem Reiter 'Extras'."
1. "Novelle im PDF-Format" habe ich ergänzt, damit deutlich wird, was gemeint ist. 'Erzählung' würde in diesem Kontext entsprechend wenig Sinn machen.
2. "Xenonauts". Eigenname, daher nicht übersetzen.
3. "Du". Ich empfehle das persönlichere Duzen, siezen ist nicht erforderlich, schon gar nicht, wenn die Übersetzung von Angehörigen aus der Spiele-Community stammt, glaube ich.

**Comment by Xenonauts** [comment]
zu 1. hört sich deutlicher an
zu 2. In diesem Kontext gebe ich dir Recht (da Organisation gemeint) würde die Soldaten/Truppen der Organisation als Xenonauten bezeichnen (ähnlich zu Astronauten)
zu 3. habe vergessen, dies nachzukorrigieren

gute Arbeit von dir soweit, weiter so ;)

**Comment by goethesfaust** [comment]
Zu 2.: Selbst da würde ich den Eigenname unübersetzt lassen, weil sich der Organisationsname auch vor allem auf seine Mitglieder bezieht und daher gleichlautend ist.

**Comment by Xenonauts** [comment]
Alles klar. Bisher bin ich solchen Stellen sowieso nicht begegnet.
