### ISSUE TITLE
8. Tipp (zeile 25)

### ISSUE THREAD

**Issue by Xenonauts** [Xenonauts/Xenonauts_DE#78]
"You can have up to three interceptors in a squadron, useful for tackling larger UFOs."

**Comment by psi-coder** [comment]
_"Du kannst bis zu drei Abfangjäger zu einer Staffel/einem Geschwader gruppieren, um größere UFOs anzugreifen."_

**Comment by goethesfaust** [comment]
"Du kannst bis zu drei Abfangjäger als (eine) Staffel aufstellen, um größere UFOs anzugreifen."
1. Ich tendiere zu "Staffel aufstellen", statt "gruppieren", da man im Kontext der Luftwaffe auch von aufgestellten Staffeln spricht. Zudem sind Staffeln wohl Geschwadern untergeordnet, weshalb ich die Bezeichnung für die entsprechend kleinere Einheit vorziehe. Zitat Wiki dazu:

"Mehrere, in der Regel zwei, fliegende Staffeln bilden bei der Luftwaffe mit der Flugbetriebsstaffel die Fliegende Gruppe innerhalb eines Geschwaders."

**Comment by Xenonauts** [comment]
Gut. Wobei im Spielkontext _"gruppieren"_ vielleicht sogar etwas besser passt.

**Comment by goethesfaust** [comment]
Ja, kann im Prinzip beibehalten werden. Wobei "aufstellen" präziser wäre.

**Comment by Xenonauts** [comment]
no problem :alien:

**Comment by Xenonauts** [comment]
_"Du kannst Staffeln aus bis zu drei Abfangjägern gegen größere UFOs oder UFO-Verbände einsetzen."_ wäre eine andere Option. Ich habe den Satz ergänzt, da Staffeln auch gegen _"Verbände von außeridischen Abfangfägern_" notwendig sind. Mit einem einzigen Abfangjäger ist da selten was zu machen; es sei denn man hat einen Maradeur/Corsair.
